# Generated by Django 3.0.8 on 2023-01-24 06:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('create_id', models.IntegerField()),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('update_id', models.IntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
